name: kleberandrade
description: Site do pesquisador, professor e programador Kleber de Oliveira Andrade.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.4.2
  font_awesome_flutter: ^8.8.1
  http: ^0.12.0+4
  flushbar: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
